### ISSUE TITLE
An error occurred while installing bootsnap (1.4.4), and Bundler cannot continue after rails new command

### ISSUE THREAD

**Issue by abrhambas01** [railsinstaller/railsinstaller-windows#107]
An error occurred while installing bootsnap (1.4.4), and Bundler cannot continue after rails new command

> An error occurred while installing bootsnap (1.4.4), and Bundler
> cannot continue. Make sure that `gem install bootsnap -v '1.4.4'
> --source 'https://rubygems.org/'` succeeds before bundling.
> 
> In Gemfile:   bootsnap

I tried installing rails with railsinstaller & followed this, since I'm a newb to ruby and stuff.: 

> https://www.tutorialspoint.com/ruby-on-rails/rails-installation.htm

and after the 
`$ rails new app` command

I encounter that error I said above

**Comment by TongzhengZeng** [comment]
I have the same problem. Have you fixed it?

**Comment by abrhambas01** [comment]
I'm not entirely sure but I think this is because of some issues conflicting with rails and windows 10, What I did is I just used rubyinstaller then installed rails after.. It's easier just forget this package.

**Comment by TongzhengZeng** [comment]
I download rubyinstaller from https://rubyinstaller.org/downloads/, the recommend version Ruby+Devkit 2.5.5-1 (x64). And then installed rails, using command: gem install rails --no-document. 
now I get rails version 5.2.3, ruby version 2.3.3p222. 
Then try to make app, using command: rails new wevapp.  Still get this problem, 
Any suggestion?
