### ISSUE TITLE
Can someone create a proper tutorial for installing rails with rails installer in windows ? 

### ISSUE THREAD

**Issue by abrhambas01** [railsinstaller/railsinstaller-windows#108]
Can someone create a proper tutorial for installing rails with rails installer in windows ? using gist ? so that there's no trouble in the future for win user.s

**Comment by okatajames** [comment]
You have to get the Rails installer from an external source. I got mine from Sourceforge, it is a complete .exe windows file.

**Comment by abrhambas01** [comment]
Just install RubyINstaller and get rails form there
