### ISSUE TITLE
Rails 6+ with Ruby 2.6+

### ISSUE THREAD

**Issue by HatsuMora** [railsinstaller/railsinstaller-windows#113]
Hi I am wondering if the owners are still watching this repo.

If so, I would like to know if I put the effort to make a ruby 2.6 with rails 6+ and send a pull request, would you take into consideration to bump up the available versions?.

Regards
-Aldo

**Comment by robertmabbs** [comment]
Hi @HatsuMora I have been working on newer versions of the RailsInstaller your very welcome to contribute.
