### ISSUE TITLE
nio4r requires Ruby version >= 2.4.

### ISSUE THREAD

**Issue by SongLiangZheng** [railsinstaller/railsinstaller-windows#115]
D:\ruby\workspace>rails new blog
      create
      create  README.md
      create  Rakefile
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in D:/ruby/workspace/blog/.git/
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/javascripts/application.js
      create  app/assets/javascripts/cable.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images/.keep
      create  app/assets/javascripts/channels
      create  app/assets/javascripts/channels/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/bundle
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/update
      create  bin/yarn
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/secrets.yml
      create  config/cable.yml
      create  config/puma.rb
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/application_controller_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/new_framework_defaults_5_1.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  test/fixtures
      create  test/fixtures/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/test_helper.rb
      create  test/system
      create  test/system/.keep
      create  test/application_system_test_case.rb
      create  tmp
      create  tmp/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  package.json
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_5_1.rb
         run  bundle install
The latest bundler is 2.2.0.rc.1, but you are currently running 1.15.3.
To update, run `gem install bundler --pre`
Fetching gem metadata from https://rubygems.org/..............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 13.0.1
Using concurrent-ruby 1.1.7
Using minitest 5.14.2
Using thread_safe 0.3.6
Using builder 3.2.4
Using erubi 1.9.0
Using mini_portile2 2.4.0
Using crass 1.0.6
Using rack 2.2.3
Fetching nio4r 2.5.4
Installing nio4r 2.5.4 with native extensions
Using websocket-extensions 0.1.5
Using mini_mime 1.0.2
Using arel 8.0.0
Using public_suffix 4.0.6
Using bindex 0.8.1
Using bundler 1.15.3
Fetching byebug 11.1.3
Installing byebug 11.1.3 with native extensions
Using childprocess 3.0.0
Using coffee-script-source 1.12.2
Using execjs 2.7.0
Using method_source 1.0.0
Using thor 1.0.1
Using ffi 1.13.1 (x86-mingw32)
Using puma 3.12.6
Using rb-fsevent 0.10.4
Fetching rubyzip 2.3.0
Installing rubyzip 2.3.0
Using tilt 2.0.10
Fetching sqlite3 1.4.2
Installing sqlite3 1.4.2 with native extensions
Using turbolinks-source 5.2.0
Using i18n 1.8.5
Using tzinfo 1.2.7
Using nokogiri 1.10.10 (x86-mingw32)
Using rack-test 1.1.0
Using sprockets 3.7.2
Gem::InstallError: nio4r requires Ruby version >= 2.4.
An error occurred while installing nio4r (2.5.4), and Bundler cannot continue.
Make sure that `gem install nio4r -v '2.5.4'` succeeds before bundling.

In Gemfile:
  rails was resolved to 5.1.7, which depends on
    actioncable was resolved to 5.1.7, which depends on
      nio4r

D:\ruby\workspace>gem install nio4r -v 2.5.4
ERROR:  Error installing nio4r:
        nio4r requires Ruby version >= 2.4.

**Comment by SongLiangZheng** [comment]
Any one help me to solve this problem. The RailsInstaller is downloaded from ruby official website

**Comment by DavidthIreland** [comment]
I have the same problem. Installed today from railsintaller for windows  Ruby 2.3

**Comment by MasoodGit** [comment]
I am facing the same issue, is there a workaround for the issue.

**Comment by sapuxx** [comment]
Same problem here. Haven't been able to find a solution

**Comment by richard-andrasek** [comment]
How I worked around this was by pointing ruby to a newer version that I had previously installed.  I did this by updating the PATH environment variable (in Windows) so that the new version of Ruby came before the older version (installed with the Rails installer). Then I re-opened my bash/command prompt and I was pointing to the newer version of ruby.

**Comment by nikolajanjic** [comment]
Thank you @richard-andrasek you helped me solve my problem. Good luck to all.

**Comment by robertmabbs** [comment]
@richard-andrasek & @nikolajanjic I know this is a more then few years old, a new RailsInstaller has been released which should sort this out with the updated ruby and rails versions.
