### ISSUE TITLE
The website does not work

### ISSUE THREAD

**Issue by faraznisar** [railsinstaller/railsinstaller-windows#116]
I try visiting the site but it won't respond.
![image](https://user-images.githubusercontent.com/35908301/118781724-fdfb7b80-b8aa-11eb-80ec-d6addb94b604.png)

Can you fix the issue soon??

**Comment by RazvanFarte** [comment]
Same for me on Chrome Version 90.0.4430.212 (Official Build) (64-bit)

**Comment by HendrikZA** [comment]
Is there any update on when the website will be available again, is still not loading from Google Chrome Version 91.0.4472.124 (Official Build) (64-bit). At this point I cant install rails on Windows. Ty

**Comment by faraznisar** [comment]
> Is there any update on when the website will be available again, is still not loading from Google Chrome Version 91.0.4472.124 (Official Build) (64-bit). At this point I cant install rails on Windows. Ty

Hello Hendrik, 

I know how frustrating it is that the website is not working. I was in your place not too long ago.

Anyways, here are the step by step instructions on how to install it without the railsinstaller website:

1. Visit https://rubyinstaller.org/downloads/ and select the version you want to download(from the list that says devkit)
2. Open the file and start the installation(don't check or uncheck anything).
3. Once the installation is complete it will open the terminal(in your case the command prompt or powershell)
4. You can just click enter for all the steps(when it asks which components shall be installed) but I personally suggest that you type in 1 the first time, 2 the second time and then 3 the last time. You can close the terminal once all three steps or pressing enter would also close the terminal.
5. Open your terminal and type in ruby --version to check the version of ruby installed (at this point you only have ruby installed and not rails)
6. Type in gem install rails --no-document (adding the --no-document flag will not download the documentation) and press enter.
7.  Type rails --version to check the version of rails.

That is all you need to do for the installation. Go ahead and create a new project.

Note: If you want to use mysql instead of mysql, you need to install ruby 2.6.7 or lower.

Hope this helps.

**Comment by HendrikZA** [comment]
> > Is there any update on when the website will be available again, is still not loading from Google Chrome Version 91.0.4472.124 (Official Build) (64-bit). At this point I cant install rails on Windows. Ty
> 
> Hello Hendrik,
> 
> I know how frustrating it is that the website is not working. I was in your place not too long ago.
> 
> Anyways, here are the step by step instructions on how to install it without the railsinstaller website:
> 
> 1. Visit https://rubyinstaller.org/downloads/ and select the version you want to download(from the list that says devkit)
> 2. Open the file and start the installation(don't check or uncheck anything).
> 3. Once the installation is complete it will open the terminal(in your case the command prompt or powershell)
> 4. You can just click enter for all the steps(when it asks which components shall be installed) but I personally suggest that you type in 1 the first time, 2 the second time and then 3 the last time. You can close the terminal once all three steps or pressing enter would also close the terminal.
> 5. Open your terminal and type in ruby --version to check the version of ruby installed (at this point you only have ruby installed and not rails)
> 6. Type in gem install rails --no-document (adding the --no-document flag will not download the documentation) and press enter.
> 7. Type rails --version to check the version of rails.
> 
> That is all you need to do for the installation. Go ahead and create a new project.
> 
> Note: If you want to use mysql instead of sqlite, you need to install ruby 2.6.7 or lower.
> 
> Hope this helps.

Thanks faraznisar this is great :)

**Comment by faraznisar** [comment]
> > > Is there any update on when the website will be available again, is still not loading from Google Chrome Version 91.0.4472.124 (Official Build) (64-bit). At this point I cant install rails on Windows. Ty
> > 
> > 
> > Hello Hendrik,
> > I know how frustrating it is that the website is not working. I was in your place not too long ago.
> > Anyways, here are the step by step instructions on how to install it without the railsinstaller website:
> > 
> > 1. Visit https://rubyinstaller.org/downloads/ and select the version you want to download(from the list that says devkit)
> > 2. Open the file and start the installation(don't check or uncheck anything).
> > 3. Once the installation is complete it will open the terminal(in your case the command prompt or powershell)
> > 4. You can just click enter for all the steps(when it asks which components shall be installed) but I personally suggest that you type in 1 the first time, 2 the second time and then 3 the last time. You can close the terminal once all three steps or pressing enter would also close the terminal.
> > 5. Open your terminal and type in ruby --version to check the version of ruby installed (at this point you only have ruby installed and not rails)
> > 6. Type in gem install rails --no-document (adding the --no-document flag will not download the documentation) and press enter.
> > 7. Type rails --version to check the version of rails.
> > 
> > That is all you need to do for the installation. Go ahead and create a new project.
> > Note: If you want to use mysql instead of sqlite, you need to install ruby 2.6.7 or lower.
> > Hope this helps.
> 
> Thanks faraznisar this is great :)

You're welcome. I'll close this issue.
