### ISSUE TITLE
Release : 3.0.0-alpha.2

### ISSUE THREAD

**Issue by karthick-manoharan** [railsinstaller/railsinstaller-windows#42]
Running `rails console` after installation brings up the below error:

```
Could not find rake-10.1.1 in any of the sources
Run `bundle install` to install missing gems.
```

After `bundle install` console works fine but starts with the below warning.

```
DL is deprecated, please use Fiddle
```

**Comment by emachnic** [comment]
Closing this old issue. If it's still a problem, please reopen.
