### ISSUE TITLE
Error running config_check.rb

### ISSUE THREAD

**Issue by bjkeith** [railsinstaller/railsinstaller-windows#51]
Hi, tried running the railsinstaller-3.1.0.exe on a 64bit Windows 7 machine as a user with admin rights.

The install seemed to go fine until the following error was displayed in a (system32) cmd shell:

C:/RailsInstaller/scripts/config_check.rb:12:in `join': no implicit conversion of nil into String (TypeError)
        from C:/RailsInstaller/scripts/config_check.rb:12:in`<main>'

Looking at config_check.rb, the offending line appears to be:

   :home        => File.join(ENV["HOMEDRIVE"], ENV["HOMEPATH"]),

Running set in another cmd shell shows these variables are set to the following values:

HOMEDRIVE=H:
HOMEPATH=\

The target computer is a corporate laptop with the HOMEDRIVE mapped to  a network share.  

Is it possible the "\" for the HOMEPATH is being interpreted as an escape char, thus giving an empty (nil) String?

**Comment by emachnic** [comment]
I'm closing this old issue. Please reopen if this is still a problem.
