### ISSUE TITLE
I downloaded the rails package that comes with Ruby2.1 from railsinstaller.com and I keep getting this error message saying there was an error downloading the gem <10.4.2>  and that bundle cannot run. Then it says "DL is deprecated, please use Fiddle." CODESCHOOL recommended to use railsinstaller.com to download the rails package but their support team said they don't know how to fix this. So please HELP!

### ISSUE THREAD

**Issue by WilfredKesh** [railsinstaller/railsinstaller-windows#57]

**Comment by lilysahifulb** [comment]
I got same thing. This is overwhelming. Any stable version for beginner to install?

**Comment by KelseyDH** [comment]
Last year I published a guide on dealing with Windows + Ruby, may or may not help in this circumstance: https://gist.github.com/KelseyDH/11198922

In regards to the Fiddle message, if I remember correctly that was just getting inserted into the command line by some gem and is nothing to worry about.

**Comment by PeterCamilleri** [comment]
To get rid of that stupid message go to 

C:\RailsInstaller\Ruby2.1.0\lib\ruby\2.1.0\dl.rb 

and comment out the line that reads: 

#warn "DL is deprecated, please use Fiddle"

and the stupid message will be gone.

**Comment by Peccavio** [comment]
The actual error is this:

Resolving dependencies...

Gem::RemoteFetcher::FetchError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certifica
te verify failed (https://rubygems.org/gems/rake-10.4.2.gem)
An error occurred while installing rake (10.4.2), and Bundler cannot continue.
Make sure that `gem install rake -v '10.4.2'` succeeds before bundling.

Is there anyway to work around it?

**Comment by Peccavio** [comment]
Workaround RubyGems' SSL errors on Ruby for Windows (RubyInstaller)
[https://gist.github.com/luislavena/f064211759ee0f806c88](https://gist.github.com/luislavena/f064211759ee0f806c88)
