### ISSUE TITLE
SSL_connect error for gem installs

### ISSUE THREAD

**Issue by dogrdon** [railsinstaller/railsinstaller-windows#58]
Initially I installed Windows railsinstaller on Windows 7 and got the same error as here http://stackoverflow.com/questions/16944224/ruby-on-rails-could-not-find-a-valid-gem-rails.

It appears that there was a problem installing gems from https://rubygems.org and it's fine if the source is set to http://rubygems.org.

Though if I try to install from Gemfile dependencies with `bundle install`, I get an error like the below for any gem that needs to be installed - looks to be the same issue but I don't know how to set the source to an unsecure connection for `bundle install`:

`Gem::RemoteFetcher::FetchError: SSL_connect returned=1 errno=0 state=SSLv3 read
server certificate B: certificate verify failed (https://rubygems.org/gems/minit
est-5.5.0.gem)
An error occurred while installing minitest (5.5.0), and Bundler cannot
continue.
Make sure that`gem install minitest -v '5.5.0'`succeeds before bundling.`

Any way to get around this that does not involve installing each gem separately?

**Update:** I suppose you could also just change the source to `source 'http://rubygems.org'` in the gemfile as well and that is a work around. But wondering if there is something more to the SSL cert verification issue.

**Comment by excid3** [comment]
Check this gist out https://gist.github.com/luislavena/f064211759ee0f806c88

**Comment by rkowalick** [comment]
If I'm reading the gist above correctly, it seems that updating the version of rubygems included in Rails Installer should fix the issue.

**Comment by kalyansagar** [comment]
add it in gem file and bundle
gem 'minitest', '~> 5.5.0'
source 'http://rubygems.org' 
thank u

**Comment by envergokmen** [comment]
I think this is big problem when you starting rails on windows. I am installing via installer but stil get ssl errors on gems. I think this have to be fixed.
