### ISSUE TITLE
cannot git clone with https 

### ISSUE THREAD

**Issue by hmspider** [railsinstaller/railsinstaller-windows#59]
git clone https://github.com/...git desplays the following error popup: 

"The program can't start  because MSVCR80.dll is missing from your computer.
Try reinstalling the program to fix this problem." (see image attached)

I did reinstall railsinstaller, same result.

![image](https://cloud.githubusercontent.com/assets/562602/5942352/dc45d9fe-a70e-11e4-90be-891ae8b753d1.png)

**Comment by emachnic** [comment]
Can you please download the latest version and try again? Going to close this for now but please reopen if it's still an issue.
