### ISSUE TITLE
read server certificate B: certificate verify failed

### ISSUE THREAD

**Issue by ahmetabdi** [railsinstaller/railsinstaller-windows#61]
While trying to install / update a gem I was getting

`ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certif
icate verify failed (https://api.rubygems.org/specs.4.8.gz)`

The fix for this was to install RubyGems 2.4.5 shouldn't this version be packaged with the installer?

This was using Ruby 2.1.5

**Comment by suyesh** [comment]
1) download this     https://raw.githubusercontent.com/rubygems/rubygems/master/lib/rubygems/ssl_certs/AddTrustExternalCARoot-2048.pem

2) put it in C:\RailsInstaller\Ruby2.1.0\lib\ruby\2.1.0\rubygems\ssl_certs

#the folder structucture might be little different than mine but you get the point. 

3) Awesomeness

**Comment by ahmetabdi** [comment]
:+1:
