### ISSUE TITLE
Rails 4.2 + Ruby 2.2 edition

### ISSUE THREAD

**Issue by radar** [railsinstaller/railsinstaller-windows#62]
Will one of these be released? I would like to recommend RailsInstaller as the preferred method to install Ruby + Rails on Windows in Rails 4 in Action. However, this is not looking likely as the latest edition is for Rails 4.1.8 and Ruby 2.1.5 and the book will be published soon.

**Comment by simi** [comment]
info about Ruby 2.2 - https://groups.google.com/forum/#!msg/rubyinstaller/OYScHEQQCIg/fkuq28gUAKsJ

**Comment by emachnic** [comment]
As soon as RubyInstaller is released with Ruby 2.2, then we can pull that in. I can, however, look into releasing a version of RailsInstaller with Rails 4.2

**Comment by OndroNR** [comment]
RubyInstaller with Ruby 2.2.1 was released 3 days ago.

**Comment by emachnic** [comment]
Ruby 2.2 seems to break certain gems, like nokogiri. I've got a package built and I may throw it on the site as a pre-release but I definitely would recommend using 2.1.5 for the time being.

**Comment by emachnic** [comment]
Some discussions on this:

- https://groups.google.com/forum/#!topic/nokogiri-talk/o-eeHJcDAqY
- http://stackoverflow.com/questions/28934078/stuck-installing-rails-rails-s-and-bundle-exec-rails-server-error

**Comment by JeffCohen** [comment]
@emachnic If it's possible/easy to do, a new release using Rails 4.2 with Ruby 2.1.5 would be super helpful, while we're waiting for the Ruby 2.2 fix.

**Comment by u007** [comment]
@JeffCohen i agree

**Comment by ravikumarjogu** [comment]
Is railsinstaller with rails 4.2 ready??

**Comment by u007** [comment]
@ravikumarjogu  u may follow instruction here to install rails4.2
https://github.com/u007/rails_for_windows/blob/master/install.bat

**Comment by emachnic** [comment]
Why don't you just use Bundler to manage the Rails dependency?

**Comment by JeffCohen** [comment]
Because for users who are installing Rails for the first time, RailsInstaller is a big help to get all of the essential tools updated. 

Whenever a new version of Rails is released, that seems like a reasonable time to update RailsInstaller so that it provides a reasonably up-to-date package.  Especially seems it only happens once or twice a year at most.

I hope that makes sense?

If not for 4.2, will RailInstaller be updated for Rails 5.0 when it is released (likely to be later this month)?

**Comment by ravikumarjogu** [comment]
I got it, thanks @emachnic

**Comment by emachnic** [comment]
There's a new version out (3.4.0). Going to close this issue but please reopen if needed.
