### ISSUE TITLE
Ruby interpeter (CUI) 2.1.5p273 [i386-mingw32] has stopped working

### ISSUE THREAD

**Issue by tames84** [railsinstaller/railsinstaller-windows#64]
I am trying to install Ruby 2.1 Windows Installer on Windows 8.1 (x64) using the railsintaller-3.1.0.exe. The install seems to work until i try opening the Command Prompt with Ruby and Rails, at which time I receive the error "Ruby interpeter (CUI) 2.1.5p273 [i386-mingw32] has stopped working".

If anyone has some insight or could provide help on this issue it would be greatly appreciated.

**Comment by emachnic** [comment]
I'm not sure that this is a RailsInstaller issue. We've just released a new version so try with that. Going to close this for now but feel free to reopen if needed.
