### ISSUE TITLE
railsinstaller 3.1.0 install failed in Windows Server 2003 32bit 

### ISSUE THREAD

**Issue by bjxiaowanzi** [railsinstaller/railsinstaller-windows#65]
Error info：

ruby.exe - 无法找到入口
无法定位程序输入点 _gmtime64_s 于动态链接库 msvcrt.dll 上

**Comment by georf** [comment]
I got the same error on XP 32 bit:
> ruby.exe - Entry Point Not Found
> The procedure entry point _gmtime64_s could not be located in the dynamic link library msvcrt.dll.

**Comment by tdvit** [comment]
hello I'm experiencing the same problem (win xp)
the installer railsinstaller-2.2.5.exe (ruby 1.9)
resolves the problem ?
regards

**Comment by emachnic** [comment]
Closing old issue. Please reopen if necessary. Also, try using the latest version.
