### ISSUE TITLE
Could not find a valid gem 'rake' 10.4.2: Unable to download data ...

### ISSUE THREAD

**Issue by andreadz** [railsinstaller/railsinstaller-windows#67]
Could not find a valid gem 'rake' 10.4.2: Unable to download data from https://rubygems.org/ - SSL connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

anyone can help me ?

**Comment by walrus1977lu** [comment]
It is necessary to write Gemfile http://rubygems.org/

**Comment by faouzzz** [comment]
Hi look here :arrow_down: 
http://stackoverflow.com/questions/19150017/ssl-error-when-installing-rubygems-unable-to-pull-data-from-https-rubygems-o/27298259#27298259

**Comment by faouzzz** [comment]
preaps need to include it in the installer...

**Comment by emachnic** [comment]
This is a known issue with upstream. Closing this issue.
