### ISSUE TITLE
Maintenance Status of RailsInstaller?

### ISSUE THREAD

**Issue by FreeApophis** [railsinstaller/railsinstaller-windows#68]
Is this project still maintained? some serious issues have not been fixed within a year now. 

The package is basically broken without a manual intervention on the ssl issue (Issue: #58), the rails and the ruby version are more than a year old two minor releases of ruby (2.2 and 2.3) and one one on rails (4.2) are not supported. (Issue: #62) And a major rails release is now in beta.

There are ancient Pull Requests still open: (#56)

With Rails 5 ahead which will require Ruby 2.2.2+ this package will soon be completley broken.

**Comment by emachnic** [comment]
@FreeApophis This project can be picked up by someone else if they would like to maintain it. However, RailsInstaller has become kinda obsolete now that there are things like Chocolatey so I question why it is still needed.

**Comment by FreeApophis** [comment]
So, the Project is dead. Fine.

Perhaps redirect the people to the alternative/s, never heard of Chocolatey before your post. At least now there is this ticket which is a clear message.

BTW I do not see why I need another package manager to install a package manager.

**Comment by emachnic** [comment]
@FreeApophis Chocolatey just makes it easier to script installing Rubyinstaller, the DevKit, Git, and anything else that RailsInstaller provides. Rubyinstaller is not a package manager so I'm not sure about that last comment. In any event, thanks for the interest in RailsInstaller.

**Comment by PeterCamilleri** [comment]
I cannot agree that Chocolatey makes RailsInstaller obsolete. The readme in it's repo cannot even be bothered to state what is is that it does. The assumption is that everyone just knows what some obscure L***x programs do. Instead, the readme goes into great lengths describing the process for reporting bugs in Chocolatey. I suppose that this level of hostility is typical in the L***x world, but to me, Chocolatey has 2.99 strikes against it.

**Comment by emachnic** [comment]
@PeterCamilleri https://chocolatey.org/ is the website and it shows the lines to install in CMD or Powershell. After that, you can just do `choco install ruby` to get the latest Rubyinstaller package. I'm happy to hand off maintenance of RailsInstaller to someone who has more Windows experience and who wants to take the project further.

**Comment by emachnic** [comment]
@PeterCamilleri @FreeApophis I just released version 3.1.1 yesterday with Ruby 2.1.8 and about to release 3.2.0 with Ruby 2.2.3 after I'm done testing it. Cheers!

**Comment by FreeApophis** [comment]
👍Great! Especially since even ruby-Langg.org is pointing to this installer!
https://www.ruby-lang.org/en/documentation/installation/#rvm

I know rails treats the windows world as a second class citizen ... hardly any gem which does not have some windows problems. I am used to that ;)

**Comment by rilut** [comment]
@emachnic but, can chocolatey's ruby install Rails 5?

**Comment by emachnic** [comment]
@rilut Once Ruby is installed, you can install whichever version of Rails you want. Best practice is to use Bundler to manage your project dependencies.

**Comment by rilut** [comment]
@emachnic do chocolatey's ruby have devkit? installing native gems often fail
