### ISSUE TITLE
Checksum error after new Rails install

### ISSUE THREAD

**Issue by JustinDDavis** [railsinstaller/railsinstaller-windows#69]
I attempted to install Rails for the first time on a windows machine, and I received this error message while attempting to create a new project. 
I used the command `rails new sample_app`

It then started to create the normal project files. It completed `create  vendor/assets/stylesheets/.keep` and attempted `run  bundle install`. 

At this point, it prints `Checksum of /versions does not match the checksum provided by server! Something is wrong.`

I found someone that had a similar issue ([link](http://stackoverflow.com/questions/35315712/rails-initialization-checksum-error)), but the solution to delete the /cache did not work on my installation.

Are there any other possible solutions?

**Comment by dacoinminster** [comment]
I just had this problem too and I think it had to do with trying to install a different version of ruby after the newest version failed to install. I fixed it by uninstalling bundler entirely and reinstalling it. Details here: http://stackoverflow.com/questions/35315712/rails-initialization-checksum-error#comment58473515_35382334

**Comment by JustinDDavis** [comment]
uninstalling Bundler and reinstalling version 1.9 did the trick. thank you for pointing me in the right direction.
