### ISSUE TITLE
problem with the Helpers Path

### ISSUE THREAD

**Issue by dezconocido** [railsinstaller/railsinstaller-windows#74]
That error is 
AbstractController::Helpers::MissingHelperError in WelcomeController#index

i have Windows 10 64 b

I've done everything but nothing is solved, what can it be?

I have a laptop with Windows 10 and if functional Rails 64b well but in my personal pc does not work.

can you help me?

**Comment by brunomilani** [comment]
Same error.

**Comment by brunomilani** [comment]
IN WINDOWS - SOLUTION

Example Folder Application:

c:/Users/username/apps/blog

I was starting my folder application in bash all lowercase path. The correct is in windows use the folder Users with the first uppercase letter.

**cd c:/## Users/username/application/application_folder**
