### ISSUE TITLE
Readline not installing or working?

### ISSUE THREAD

**Issue by latazzajones** [railsinstaller/railsinstaller-windows#75]
In windows - it looks like readline is either not being installed or not working for version 2.2

**Comment by emachnic** [comment]
Can you be about more specific? Are you getting errors? What about command line output?

Thanks

**Comment by latazzajones** [comment]
I can try - it was something I noticed when trying to use rails installer with students at a rails workshop this past weekend. Some students lost the ability to use backspace and up keys in the command line. There was no unexpected output from the command line .. no error message.

We were able to get backspace working again by setting `IRB.conf[:USE_READLINE] = false` in a ~/.irbrc file on the student's machines or starting the console with the `--noreadline` flag.

**Comment by emachnic** [comment]
On first thought, this doesn't sound like an issue with Railsinstaller. Have you checked the readline issues?

**Comment by emachnic** [comment]
Closing as this doesn't seem like a RailsInstaller issue
