### ISSUE TITLE
rails --version

### ISSUE THREAD

**Issue by suryazi** [railsinstaller/railsinstaller-windows#79]
Hi,

     I installed railsinstaller-3.2.0 on windows 10 64-bit system. When in run the command ruby --version it is giving message ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]. When i run the command rails --version it is giving message "The system cannot find the path specified".

**Comment by thiagodelgado111** [comment]
I guess it's the same problem of #72.

**Comment by suryazi** [comment]
I agree, this is same as problem #72.
