### ISSUE TITLE
tiny-tds not working on Windows 10 64bit

### ISSUE THREAD

**Issue by Rajeev-Jha-RJ** [railsinstaller/railsinstaller-windows#86]
Checked with both versions download  (2.1.x) and (2.2.x).
Error:
C:/RailsInstaller/Ruby2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- tiny_tds/tiny_tds (LoadError)

Works for install: railsinstaller-3.0.0.exe
for ruby 2.0.0p598 (2014-11-13) [i386-mingw32]

**Comment by hkvajjha** [comment]
Even we are facing the same issue on x64 windows 10 with sqlserver 2014

**Comment by emachnic** [comment]
Please try with the latest version.

**Comment by robertmabbs** [comment]
I believe this issue would have been fixed in the new version of RailsInstaller, if not please reopen.
