### ISSUE TITLE
Ruby gems not abke to upgrade

### ISSUE THREAD

**Issue by dongodam** [railsinstaller/railsinstaller-windows#87]
Hey every one,  tried to upgrade the rubygems from 2.5 to 2.6.8 but wasnt able to successfully. Ran the upgrade through the command prompt, it said upgrade installation was successful then i typed in "update_rubygems --no-document" and then proceeded with "gem -v" to check the version it still came out 2.5. Triedexiting command prompt and opening it again and did gem-v still came out the same, tried restarting the pc still the same. Please help

**Comment by emachnic** [comment]
I don't think this is a RailsInstaller issue. Maybe check with the Rubygems team.
