### ISSUE TITLE
RailsInstaller 3.3 still broken like 3.2

### ISSUE THREAD

**Issue by wendyjw** [railsinstaller/railsinstaller-windows#89]
many .bat file has hard-coded `@"C:\Users\emachnic\GitRepos\railsinstaller-windows\stage\Ruby2.3.0\bin\ruby.exe`

I fix it by replace all `C:\Users\emachnic\GitRepos\railsinstaller-windows\stage\Ruby2.3.0\bin\ruby.exe` to `ruby.exe`

I notice the hard-coded bug seems to be a long time, is this a test for us?

**Comment by LCastr0** [comment]
I had the same issue, thought my installer was broken, installed again and didn't work, then I saw some threads on StackOverflow and that helped.

**Comment by orngreen** [comment]
Can confirm this as of yesterday (april 3) ... replacing user emachnic is not the first time for me  either :)

**Comment by emachnic** [comment]
Please try with the latest version.
