### ISSUE TITLE
assets (images) are all zero length

### ISSUE THREAD

**Issue by netpenthe** [railsinstaller/railsinstaller-windows#92]
Rails: 4.1.16
Ruby: 2.2, 2.3, 2.1.5 (tried all 3)

My webrick server runs OK but no images are served from /assets (css/js is fine)

When I try to do a wget on an image - it shows a 5 byte length file:
![image](https://cloud.githubusercontent.com/assets/880203/22531849/7f90c372-e933-11e6-9af8-491c639cb4c0.png)

Any ideas what this could be?

**Comment by emachnic** [comment]
I think this is more a question for the Rails team.
