### ISSUE TITLE
Possible problem in setup_environment.bat

### ISSUE THREAD

**Issue by cqcn1991** [railsinstaller/railsinstaller-windows#95]
Here is the problem that I have:
I uninstalled previous RailsInstaller on windows, and download and installed the new version (so I can upgrade to Rails 5).

After install, I open the `Command Prompt with Ruby and Rails` as ususal, and run `bundle install`, the system tells me it can't find it. As I notice, it should be the problem in `setup_environment.bat`

![qq](https://cloud.githubusercontent.com/assets/2425141/25300934/8fdb75a8-274d-11e7-9e03-c8cf065d5e3f.png)

Here the chinese simply tells that it can't find the path

I take look at the `setup_environment.bat`, I think the problem might be this line 

`SET PATH=%RUBY_DIR%\bin;%RUBY_DIR%\lib\ruby\gems\1.9.1\bin;%ROOT_DIR%\DevKit\bin;%PATH%`

https://github.com/railsinstaller/railsinstaller-windows/blob/7082b2dbc5036ce39c53f20416898cabdd0b12ca/resources/railsinstaller/setup_environment.bat#L25

Since we don't have 1.9.1 and the `bin` at all.

**Comment by Sylhare** [comment]
Hi!
I've downloaded it as well and it I had the same kind of errors (for rails.bat and bundle.bat) solved thanks to [#72](https://github.com/railsinstaller/railsinstaller-windows/issues/72) and [#70](https://github.com/railsinstaller/railsinstaller-windows/issues/70).

But I'm wondering, if there's a way to correct that so we don't run into issue #70 and #72 when installing it. Like here, the version `1.9.1` should not be hardcoded.
