### ISSUE TITLE
Ruby 2.4.1

### ISSUE THREAD

**Issue by laukstein** [railsinstaller/railsinstaller-windows#96]
Any ETA to include latest Ruby 2.4.1 https://www.ruby-lang.org/en/downloads/ ?

    > gem update
    Updating did_you_mean
    ERROR:  Error installing did_you_mean:
            did_you_mean requires Ruby version >= 2.4.0.

**Comment by laukstein** [comment]
> gem update
    Updating did_you_mean
    ERROR:  Error installing did_you_mean:
            did_you_mean requires Ruby version >= 2.4.0.

**Comment by emachnic** [comment]
Hi @laukstein,

I'm not sure on a timeframe for Ruby 2.4. We just released version 3.4.0 with Ruby 2.3.3. However, RubyInstaller has changed its DevKit installation and we're looking into how we can make use of it.

**Comment by ashmaroli** [comment]
@emachnic How about trying to setup a release with Ruby 2.3.5..? It's seems to be a serious security-fix release and see no indication of it being released by RubyInstaller or RubyInstaller2..

**Comment by emachnic** [comment]
@ashmaroli I'll look into getting that released. Should be an easy bump.

**Comment by ashmaroli** [comment]
Awesome! Thanks :smiley:

**Comment by emachnic** [comment]
@ashmaroli Apologies, but I just checked and there has not been a release of Ruby 2.3.5 from RubyInstaller. Gonna have to wait for that before we can update ours.

**Comment by ashmaroli** [comment]
@robertmabbs Wow! I had no idea this project had resumed development. Thank you for shipping a new release.
