### ISSUE TITLE
in railsinstaller-3.3.0 all *.bat files in .\Ruby2.3.0\bin\ use folder C:\Users\emachnic\

### ISSUE THREAD

**Issue by Jinjinov** [railsinstaller/railsinstaller-windows#99]
in railsinstaller-3.3.0 all *.bat files in .\Ruby2.3.0\bin\ use folder

C:\Users\emachnic\GitRepos\railsinstaller-windows\stage\Ruby2.3.0\bin\ruby.exe

this path does not exist

**Comment by emachnic** [comment]
@Jinjinov can you please download the latest version and let me know if this is resolved?
